name: smoke
on: { workflow_dispatch: {} }

jobs:
  ping:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - run: |
          echo "hello from $(hostname)"
          echo "uname: $(uname -a)"
          echo "runner: $RUNNER_NAME / $RUNNER_OS / $RUNNER_ARCH"
          curl -sI https://api.github.com | head -n1
