name: smoke
on:
  workflow_dispatch:
    inputs:
      triton_ref:
        description: "Triton tag/branch/commit"
        required: false
        default: v3.3.0  

jobs:
  ping:
    runs-on: [self-hosted]   # broad match; no custom label required
    timeout-minutes: 5
    steps:
      - run: |
          echo "hello from $(hostname)"
          echo "uname: $(uname -a)"
          curl -sI https://api.github.com | head -n1
