name: build-triton-cp38-aarch64
on:
  workflow_dispatch:
    inputs:
      triton_ref:
        description: "Triton tag/branch/commit"
        required: false
        default: "v2.1.0"
      jobs:
        description: Number of parallel cores
        required: false
        default: "96"

jobs:
  wheel:
    runs-on: self-hosted
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v4
        with:
          repository: triton-lang/triton
          fetch-depth: 0

      - name: Select ref
        run: |
          set -eux
          REF="${{ inputs.triton_ref }}"
          git fetch --all --tags --force
          if git rev-parse "refs/tags/$REF" >/dev/null 2>&1; then
            git -c advice.detachedHead=false checkout "refs/tags/$REF"
          elif git rev-parse "origin/$REF" >/dev/null 2>&1; then
            git checkout "origin/$REF"
          else
            git checkout "$REF"
          fi
          git submodule update --init --recursive
          git rev-parse --short HEAD

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-

      - name: (Optional) Prune old Docker stuff
        run: |
          sudo docker system prune -af --volumes || true

      - name: Build cp38 wheel in CUDA-manylinux (aarch64)
        run: |
          ( while true; do echo "::notice::build still running $(date -u)"; sleep 60; done ) & HB=$!
          docker run --rm \
            -e JOBS='${{ inputs.jobs }}' \
            -e PIP_NO_CACHE_DIR=1 \
            -e TRITON_DISABLE_PTXAS_DOWNLOAD=1 \
            -e TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas \
            -v "$PWD":/io -w /io/python \
            sameli/manylinux_2_28_aarch64_cuda_12.3 bash -lc '
              set -eux
              PYBIN=/opt/python/cp38-cp38/bin

              # toolchain inside container
              $PYBIN/pip install -U pip setuptools wheel cmake ninja auditwheel

              # use all cores unless input provided
              if [ -z "${JOBS:-}" ]; then
                J=$(nproc)
              else
                J="$JOBS"
              fi
              LJ=$(( J/4 + 1 )); [ "$LJ" -lt 1 ] && LJ=1

              # ensure we are using the container's native ARM ptxas
              command -v ptxas
              file $(command -v ptxas) || true
              ptxas --version || true

              # make sure any stale vendored cuda dir can’t override our ptxas
              rm -rf /io/python/triton/third_party/cuda || true

              export CC=gcc CXX=g++ CFLAGS="-march=armv8-a" CXXFLAGS="-march=armv8-a"
              export TRITON_CMAKE_FLAGS="
                -DCMAKE_BUILD_TYPE=Release
                -DLLVM_ENABLE_ASSERTIONS=OFF
                -DLLVM_ENABLE_PROJECTS=mlir;llvm;lld
                -DLLVM_TARGETS_TO_BUILD=AArch64;NVPTX
                -DLLVM_INCLUDE_TESTS=OFF
                -DLLVM_INCLUDE_EXAMPLES=OFF
                -DLLVM_OPTIMIZED_TABLEGEN=ON
              "
              export CMAKE_BUILD_PARALLEL_LEVEL="$J"
              export LLVM_PARALLEL_COMPILE_JOBS="$J"
              export LLVM_PARALLEL_LINK_JOBS="$LJ"
              export NINJAFLAGS="-v -j$J -l$J"

              # build & manylinux-repair
              $PYBIN/pip wheel --no-deps -w /io/wheelhouse .
              auditwheel repair /io/wheelhouse/triton-*.whl -w /io/wheelhouse

              # drop the pre-repair linux_aarch64 wheel to avoid duplicates
              rm -f /io/wheelhouse/triton-*-linux_aarch64.whl || true

              ls -lh /io/wheelhouse/
            '
          kill $HB || true

      - uses: actions/upload-artifact@v4
        with:
          name: triton-aarch64-cp38
          path: wheelhouse/*.whl
          retention-days: 30
