name: build-triton-cp38-aarch64
on:
  workflow_dispatch:
    inputs:
      triton_ref:
        description: "Triton tag/branch/commit"
        required: false
        default: v3.3.0

jobs:
  wheel:
    runs-on: [self-hosted, linux, arm64, arm64-big]  # labels from the runner VM
    timeout-minutes: 360

    steps:
      - name: Checkout Triton source
        uses: actions/checkout@v4
        with:
          repository: triton-lang/triton
          fetch-depth: 0

      - name: Select ref
        run: |
          set -eux
          REF="${{ inputs.triton_ref }}"
          git fetch --all --tags --force
          if git rev-parse "refs/tags/$REF" >/dev/null 2>&1; then
            git -c advice.detachedHead=false checkout "refs/tags/$REF"
          elif git rev-parse "origin/$REF" >/dev/null 2>&1; then
            git checkout "origin/$REF"
          else
            git checkout "$REF"
          fi
          git submodule update --init --recursive
          git rev-parse --short HEAD

      - name: Build cp38 wheel in manylinux (aarch64)
        run: |
          ( while true; do echo "::notice::build alive $(date -u)"; sleep 60; done ) & HB=$!
          docker run --rm -v "$PWD":/io -w /io/python quay.io/pypa/manylinux_2_28_aarch64 bash -lc '
            set -eux
            PYBIN=/opt/python/cp38-cp38/bin
            $PYBIN/pip install -U pip setuptools wheel cmake ninja auditwheel ccache
            export CCACHE_DIR=/io/.ccache
            export CC="ccache gcc" CXX="ccache g++"
            export TRITON_CMAKE_FLAGS="
              -DCMAKE_BUILD_TYPE=Release
              -DLLVM_ENABLE_ASSERTIONS=OFF
              -DLLVM_ENABLE_PROJECTS=mlir;llvm;lld
              -DLLVM_TARGETS_TO_BUILD=AArch64;NVPTX
              -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF
              -DLLVM_OPTIMIZED_TABLEGEN=ON
              -DCMAKE_C_FLAGS=-march=armv8-a -DCMAKE_CXX_FLAGS=-march=armv8-a
              -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            "
            export CMAKE_BUILD_PARALLEL_LEVEL=12 LLVM_PARALLEL_COMPILE_JOBS=12 LLVM_PARALLEL_LINK_JOBS=4
            export NINJAFLAGS="-j12 -l12 -v"
            $PYBIN/pip wheel --no-deps -w /io/wheelhouse .
            auditwheel repair /io/wheelhouse/triton-*.whl -w /io/wheelhouse
            rm -f /io/wheelhouse/triton-*-linux_aarch64.whl || true
          '
          kill $HB || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-aarch64-cp38
          path: wheelhouse/*.whl
          retention-days: 30

      - name: Publish GitHub Release (stable URL)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: triton-cp38-aarch64-${{ github.run_number }}
          name: Triton cp38 aarch64 ${{ github.run_number }}
          prerelease: true
          files: wheelhouse/*.whl
