name: build-triton-cp38-aarch64
on:
  workflow_dispatch: {}

jobs:
  wheel:
    runs-on: ubuntu-24.04-arm   # native arm64 hosted runner
    timeout-minutes: 240
    steps:
      - name: Checkout Triton source
        uses: actions/checkout@v4
        with:
          repository: triton-lang/triton
          ref: v3.5.0           # choose the version/tag you want

      - name: Build cp38 wheel in manylinux (aarch64)
        run: |
          docker run --rm -v "$PWD":/io -w /io quay.io/pypa/manylinux_2_28_aarch64 bash -lc '
            set -eux
            /opt/python/cp38-cp38/bin/pip install -U pip build cmake ninja auditwheel
            export CC=gcc CXX=g++ CFLAGS="-march=armv8-a" CXXFLAGS="-march=armv8-a"
            /opt/python/cp38-cp38/bin/python -m build --wheel
            auditwheel repair dist/*.whl -w wheelhouse
            rm -rf dist
          '

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-aarch64-cp38
          path: wheelhouse/*.whl
