name: build-triton-cp38-aarch64
on:
  workflow_dispatch: {}

jobs:
  wheel:
    runs-on: ubuntu-24.04-arm   # native arm64 hosted runner
    timeout-minutes: 240
    steps:
      - name: Checkout Triton source
        uses: actions/checkout@v4
        with:
          repository: triton-lang/triton
          ref: v3.3.0

      - name: Build cp38 wheel in manylinux (aarch64)
        run: |
          docker run --rm -v "$PWD":/io -w /io/python quay.io/pypa/manylinux_2_28_aarch64 bash -lc '
            set -eux
            PYBIN=/opt/python/cp38-cp38/bin
            $PYBIN/pip install -U pip setuptools wheel cmake ninja auditwheel
            # Keep CPU baseline generic for Jetson
            export CC=gcc CXX=g++ CFLAGS="-march=armv8-a" CXXFLAGS="-march=armv8-a"
            # Optional: keep link/compile parallelism reasonable
            export MAX_JOBS=16 LLVM_PARALLEL_COMPILE_JOBS=16 LLVM_PARALLEL_LINK_JOBS=4
            # Build wheel for the package in /io/python
            $PYBIN/pip wheel --no-deps -w /io/wheelhouse .
            # Repair to manylinux policy (bundles needed libs except glibc)
            auditwheel repair /io/wheelhouse/triton-*.whl -w /io/wheelhouse
          '


      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-aarch64-cp38
          path: wheelhouse/*.whl
